// Generated by https://quicktype.io

export interface IMDBResponse {
  d?: D[];
  q: string;
  v: number;
}

export interface D {
  i: I;
  id: string;
  l: string;
  rank: number;
  s: string;
  v?: V[];
  vt?: number;
  q?: string;
  y?: number;
  yr?: string;
}

export interface I {
  height: number;
  imageUrl: string;
  width: number;
}

export interface V {
  i: I;
  id: string;
  l: string;
  s: string;
}
